app:
  image: busybox
  environment:
    - ENVIRONMENT=development
  working_dir: /shared
  volumes:
    # app
    - ./src:/shared/src:ro
    # nginx
    - ./environment/nginx/config:/shared/nginx/config:ro
    - ./environment/nginx/log:/shared/nginx/log

nginx:
  build: ./environment/nginx/
  ports:
    - "80:80"
  volumes_from:
    - app